[build]
builder = "NIXPACKS"
buildCommand = "task build-worker"
watchPatterns = ["worker/**","shared/**"]
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "bin/worker"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10