[build]
builder = "NIXPACKS"
buildCommand = "task build-scheduler"
watchPatterns = ["scheduler/**","shared/**","prisma/**"]
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "bin/scheduler"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10